### PR TITLE
Task view updates

### PR DESCRIPTION
**Pull request by soft-Dev**
Updated Task View Bezl:
 - Ability to update individual tasks
 - Complete functionality working
 - Bug fixes in crm.js

### CODE REVIEW

**Comment by bitingmidge** [comment]
I have a few questions about this pull request. It appears that some of the following files may just be accidental commits of simple whitespace formatting changes cause by your IDE but I want to be sure...

**_libraries/versions/1.3/epicor/crm.js_**
Is this a hot fix against the 1.3 version of this library file? If so the main libraries/epicor/crm.js file should also be updated with the same changes. Also there is a 1.4 version that has been released. I would assume that would need the same changes applied as well?

_**roles/sales-rep/tasks-view/versions/1.1/js/onDataChange.js
roles/sales-rep/tasks-view/versions/1.1/js/onStartup.js
roles/sales-rep/tasks-view/versions/1.1/js/task.js**_
Are these hot fixes against the 1.1 version? If so the changes should probably also be applied to the main development files.

_**roles/sales-rep/tasks-view/versions/1.2/BezlExport.txt
roles/sales-rep/tasks-view/versions/1.2/js/onDataChange.js
roles/sales-rep/tasks-view/versions/1.2/js/onStartup.js
roles/sales-rep/tasks-view/versions/1.2/js/task.js
roles/sales-rep/tasks-view/versions/1.2/sql/Epicor10/GetAccountsTasks.sql
roles/sales-rep/tasks-view/versions/1.2/sql/Epicor10/GetTaskTypes.sql
roles/sales-rep/tasks-view/versions/1.2/sql/Epicor905/GetAccountsTasks.sql
roles/sales-rep/tasks-view/versions/1.2/sql/Epicor905/GetTaskTypes.sql**_
It looks like you've made a new 1.2 version of the "Tasks View" bezel. Don't forget to also commit any of the main development files that changed. (e.g. roles/sales-rep/tasks-view/BezlExport.txt).

**Comment by soft-Dev** [comment]
@bitingmidge 
**libraries/versions/1.3/epicor/crm.js**
I've updated all versions of the crm.js file as well as the base with this hotfix.

**roles/sales-rep/tasks-view/versions/1.1/js/onDataChange.js
roles/sales-rep/tasks-view/versions/1.1/js/onStartup.js
roles/sales-rep/tasks-view/versions/1.1/js/task.js**
I had originally been making my changes to 1.1, but decided to make 1.2 instead, so this is just white space formatting.

**roles/sales-rep/tasks-view/versions/1.2/BezlExport.txt
roles/sales-rep/tasks-view/versions/1.2/js/onDataChange.js
roles/sales-rep/tasks-view/versions/1.2/js/onStartup.js
roles/sales-rep/tasks-view/versions/1.2/js/task.js
roles/sales-rep/tasks-view/versions/1.2/sql/Epicor10/GetAccountsTasks.sql
roles/sales-rep/tasks-view/versions/1.2/sql/Epicor10/GetTaskTypes.sql
roles/sales-rep/tasks-view/versions/1.2/sql/Epicor905/GetAccountsTasks.sql
roles/sales-rep/tasks-view/versions/1.2/sql/Epicor905/GetTaskTypes.sql**
I did make 1.2 as the changes started adding up. I added the new BezlExport.txt for 1.2, but nothing changed for the base BezlExport.txt, so I didn't change that one. 

Let me know if I'm way off on any of this!

**Comment by bitingmidge** [comment]
@soft-Dev I think the only other thing we need to adjust is that there might be some other top level files besides the BezlExport.txt that need updated. Essentially all files at the "base" of the directory would match all files in a "versioned" directory at the time of a release. So the "BezlExport.txt" and all files in the "js" and "sql" files should match. For example, if roles/sales-rep/tasks-view/versions/1.2/js/onDataChange.js is updated then roles/sales-rep/tasks-view/js/onDataChange.js needs to match it.

If it helps in the future, if you set the version variable in the setConfig() of the bezel to an empty string ("unversioned" so to speak) then it points to the top level files and you can do all of your development off those. Then, when a release is made it's just a matter of copying all the top level files into a "versions/x.x" directory.

**Comment by soft-Dev** [comment]
Ahhh, I think I understand what I'm missing. For some reason, I had assumed the base was less than version 1.0, sort of like a basic beta. But base always matches the latest. I'll update accordingly.

**Comment by bitingmidge** [comment]
@soft-Dev No problem. It is confusing, and the worst part is it's not currently properly documented anywhere (other than in a closed issue I believe.)

**Comment by soft-Dev** [comment]
@bitingmidge I've just updated the base files and pushed those if you want to take another look.

**Comment by bitingmidge** [comment]
@soft-Dev Looks good! Thanks for taking care of that.

**Comment by soft-Dev** [comment]
Thanks for working through it with me!

**Pull request merged**
