### PR TITLE
Task view updates rev2

### PR DESCRIPTION
**Pull request by soft-Dev**
Modifications to version 1.2 requested by Sunlight.

### CODE REVIEW

**Comment by bitingmidge** [comment]
@soft-Dev Just one issue I noticed, the library versioning should follow the same format as the individual apps. So, if there is a change to the `libraries/versions/1.4/epicor/crm.js` file then the `libraries/epicor/crm.js` should match it.

**Comment by soft-Dev** [comment]
@bitingmidge Sorry about that, this is done.

**Comment by bitingmidge** [comment]
@soft-Dev Did you push that change to this development branch? I'm not seeing it in the pull request.

**Comment by soft-Dev** [comment]
@bitingmidge Ha, definitely committed locally and forgot to push. Should be seeing it now.

**Comment by bitingmidge** [comment]
@soft-Dev Awesome! Thank you.

**Comment by soft-Dev** [comment]
Thank you!

**Pull request merged**
