### PR TITLE
Add ceo inventory valuation by age #370

### PR DESCRIPTION
**Pull request by aellis**

### CODE REVIEW

**Comment by bitingmidge** [comment]
@aellis Looks very nice! Found one oddity...

1. adjust the sliding scale to adjust the min/max age (data that falls outside the range gets greyed out correctly)
1. click anywhere on the chart
1. The sliding scale is reset to the largest min/max age but the visual representation of the chart doesn't reset (the boxes that were greyed out remain that way)

**Comment by aellis** [comment]
@bitingmidge that is going to be something we'd have to take up with Fusion Charts support.  I suggest we go ahead and pull this one in and open a ticket up with them.

**Comment by bitingmidge** [comment]
@aellis The issue is being caused by this code:
```
// Prevent the drill-down logic as it is too taxing on mobile devices
bezl.vars.chart.addEventListener("beforeDrillDown", function(eventObj, dataObj) {
    eventObj.preventDefault();
    eventObj.stopPropagation();
});
```
It works correctly if you comment that out because it is resetting the slider control in preparation of the drill down screen.

**Comment by aellis** [comment]
Ahh - gotcha.  This is a tough one because if we put that back in this is unusable on anything other than a full desktop PC (so we add a new bug) but if we leave it we have the bug you have noted here.  The other option I suppose is just to remove the sliding scale all together, but I am not sure I am thrilled about that.  Let's accept this one as it is and open an issue to consider which way is best to resolve this.

**Pull request merged**
