### PR TITLE
Add common / company calendar #350

### PR DESCRIPTION
**Pull request by aellis**

### CODE REVIEW

**Comment by bitingmidge** [comment]
@aellis I'm getting the following error:
`TypeError: Cannot set property 'events' of undefined`

It's coming from line 5 in onDataChange.js:
`bezl.vars.config.calendarOptions.events = [];`

Looks like bezl.vars.config.calendarOptions isn't getting set?

**Comment by bitingmidge** [comment]
@aellis That fixed that issue. I'm getting a different issue in both Chrome and Safari. It doesn't prevent the page from rendering in Chrome or the iOS Safari browser but it does prevent it from working in the macOS Safari browser.

`Uncaught SyntaxError: Unexpected token <` in the `fullcalendar.min.js` file.

In the debugger it looks like it is using the dist/fullcalendar.min.js file which has \<html\> output at the top of the file (and thus the error) instead of the "fullcalendar/dist/fullcalendar.min.js" file which is pure javascript.

screenshot 2017-08-09 15 58 23

Don't know if that makes any sense.

**Comment by aellis** [comment]
This might have been a tweak I was trying to slip under the rug for that pull request.  Can you try it again?

**Comment by bitingmidge** [comment]
The calendar does render correctly in Safari now. However, I am still getting the same error in the console from the dist/fullcalendar.min.js file that is actually HTML and not JavaScript.

screenshot 2017-08-10 09 20 30

Not sure where that is coming from.

**Comment by aellis** [comment]
Alright – I just ended up pulling that require statement out completely.  It seemed like it started to conflict when I had the right path in there.

Thanks,
Adam

adam ellis | operations manager
saberlogic | 132 main street | wadsworth, ohio 44281
855.335.6442 x104 | direct: 330.697.3883 | www.saberlogic.com<http://www.saberlogic.com/>
[Description: Description: sl-email-ltgreen]

**Pull request merged**
