### PR TITLE
Add crm call functionality into accounts view #360

### PR DESCRIPTION
**Pull request by aellis**
This is a new version of accounts view that builds the CRM calls directly in via a button you click on the drill-down.  I believe this should actually deprecate the stand-alone CRM calls app.  There are a few spots where we do not yet have feature parity:

1.  I do not have a filter box on the call log.
2.  There is not the automatic call log detail recording when you click phone, address, or e-mail.

We will need to do these as a 1.3 release as I had a customer that needed an immediate fix for the CRM calls which were not working well on the existing Bezl.  So upon accepting this pull request:

1. Open issues to add filter and automatic call log details to account view.  The filter box should be fairly self-explanatory but the automatic call log details should be vastly simplified over how we had it before.  It should simply record the appropriate values into the bezl.vars fields for the new call log entry and clear them out if a different customer is selected.

2.  I would also suggest we do an issue to add tasks to 1.3 so we can deprecate that app as well.

3.  Please do *not* automatically delete the feature branch here upon accepting the pull request as I currently have a customer testing this and actively pointing to my feature branch via rawgit.  I will need to update their setConfig when this hits dev.

### CODE REVIEW

**Comment by bitingmidge** [comment]
Closes #360

**Comment by bitingmidge** [comment]
@aellis In both Chrome and Safari on the desktop I am having trouble getting the pop-up window to close. Tested with the "Close" button, the 'x' in the upper right hand corner, and clicking on the main window outside of the popup. It does work on mobile devices however.

**Comment by aellis** [comment]
@bitingmidge can you try this out again when you get a chance?  The issue is that bootstrap modals do not seem to play nice with angular2-grid.  If the grid was disabled this would work fine.  I switched to a p-dialog which seems better in every way.

**Comment by bitingmidge** [comment]
@aellis The new p-dialog seems to work well.

One additional corner case I noticed during testing is that, on a handheld device, if you switch between  orientations (portrait <-> landscape) the p-dialog will display for the previous orientation, often partially off the screen. If you reload the page in the new orientation it will work correctly.

I'm wondering if we shouldn't store the dialog width/height in ngOnInit() and instead re-evaluate it overtime the dialog is displayed?

**Comment by aellis** [comment]
@bitingmidge lets just accept this one and open an issue with that corner case.  The main reason being that it looks like rawgit is down again now and I have a customer using this version pointed to this feature branch.

**Comment by aellis** [comment]
@bitingmidge it looks like rawgit just came back up so no huge rush on this, I still agree though that the sizing of the p-dialog on orientation change can probably go in as an issue.

**Comment by bitingmidge** [comment]
@aellis I've merged the pull request into development, created the follow up issues, and did **_not_** delete the branch for the time being.

**Pull request merged**
