### PR TITLE
Calls view customer selector

### LINKED ISSUE #313: Sales-Rep CRM Calls View - Selected Customer Dropdown
Just like the inquiry bezls, there was a request to add an ability to select different customers from the bezl. We can use the same technique we used for the inquiry bezls; a dropdown selector.

### PR DESCRIPTION
**Pull request by NDMO**
Closes #313 . Adds a customer selector drop down to call viewer, includes an all accounts option

### CODE REVIEW

**Comment by bitingmidge** [comment]
The "More" button functionality seems to have regressed a little bit with the addition of the new dropdown. I think we might need to reset `bezl.vars.loadedMore = false` when selecting a new customer from the list. We also might not want to allow the "More" button to be available when "All Accounts" is selected. That would probably pull a lot of data.

**Comment by NDMO** [comment]
@bitingmidge I will take a look, I did notice that the getAllCalls query will only pull in the last 30 days.

**Comment by bitingmidge** [comment]
@NDMO That might not be too bad then. 

This is a little confusing but the one SQL file is everything in the last 90 days and the other one for All Accounts has a TOP 100 qualifier at the top. I don't think the "More" button is really doing anything at the moment because I think it is running the same SQL that gets called when the customer is selected at the list. I think the original intention was that the initial CRM calls to load up would be everything in the last 90 days, and clicking "More" would load up the TOP 100.

A second thing I'm noticing is that selecting a different Account in the Account View bezl selects the correct account in the dropdown but no calls get loaded up. Are you seeing the same thing?

**Comment by NDMO** [comment]
@bitingmidge good catch on the account selection not triggering a search. I committed a fix for that. 
Do you want me changing something for the 'more' button?

**Comment by bitingmidge** [comment]
@NDMO I think at the very least we should re-enable the button (in case it was clicked) after selecting a new account from the dropdown. I think that involves setting `bezl.vars.loadedMore` back to false.

**Comment by NDMO** [comment]
@bitingmidge , I set the loadedmore to false on the dropdown selection. Talked to adam yesterday, he mentioned we should probably rework that loadedmore, so Ill open a different ticket for that.

**Pull request merged**
