### PR TITLE
Add ceo comparative sales breakdowns #364

### PR DESCRIPTION
**Pull request by aellis**

### CODE REVIEW

**Comment by bitingmidge** [comment]
@aellis The main screen looks good. When I click on it for the details, the drill down screens are empty.

screenshot 2017-08-21 14 14 16
screenshot 2017-08-21 14 14 29

**Comment by aellis** [comment]
@bitingmidge is it possible you had an older sales.xlsx here?  I just tried again and this is still working for me.  If it still isn't working, could you throw a raw data view to see what it is pulling fro you?

**Comment by bitingmidge** [comment]
@aellis I think I have the latest spreadsheet, and I do get raw data returned in the form of:
```
{
    "Column1": "Sum of LineTotal",
    "Column2": "Column Labels",
    "Column3": null,
    "Column4": null
  },
  {
    "Column1": "Row Labels",
    "Column2": "2016",
    "Column3": "2017",
    "Column4": "Grand Total"
  },
```

It looks like the problem for me is that the bezel is expecting the json data keys to have a space in-between the "Column" and the number like so:

screenshot 2017-08-22 13 47 36

**Comment by aellis** [comment]
@bitingmidge thanks for the insight.  There must be some browser / OS level stuff going on there getting rid of those spaces.  It is probably better for me to be giving the columns better names anyways - try the latest version and let me know if it works for you.

**Comment by aellis** [comment]
@bitingmidge oh, and also note that I pushed a new XLSX file that is smaller in size.  The whole SUMIFS thing I was doing previously was neat and all but it took it was a bit CPU heavy on the BRDB side and made these metrics a bit less poppy.

**Comment by bitingmidge** [comment]
Closes #364

**Pull request merged**
