### PR TITLE
Geolocation bezl

### LINKED ISSUE #29: Sales Rep - Map View - Geocode Logic
As a part of sales-rep.map-view we have a routine that will geocode the addresses that do not currently have a defined geocode, but this seems to only work for about 10 entries at a time.  We have not done enough investigation to know for certain, but it seems like Google is halting the script after a period of time.  To remedy this, try putting the process that does the geocoding on a setTimeout so that it does the lookups in bursts *or* see if there is a better way to be doing this in mass with the Google API.

### PR DESCRIPTION
**Pull request by NDMO**
Closes #29 . Available on sales-rep on the geocoder panel.

### CODE REVIEW

**Comment by aellis** [comment]
@NDMO when I ran this, it never completed the 'Finishing Up' stage although it did successfully geocode a sizable number of the addresses for me.  Can you see what is going on there?

**Comment by aellis** [comment]
@NDMO I see a conflict on this one related to map-view.  Was that an accidental commit into this branch?  I would think this app should have it's own copy of that JS file, even if they are largely identical.

**Comment by aellis** [comment]
@NDMO btw, great work on this Geocoder - it works really slick!

**Comment by aellis** [comment]
I seem to be encountering this error at times when running this:

Uncaught TypeError: Cannot read property 'data' of undefined
    at https://rawgit.com/bezlio/bezlio-apps/geolocation-bezl/roles/common/geolocation/js/map.js:58:96
    at e.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.min.js:1:15126)
    at n.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.min.js:1:12486)
    at invoke (http://localhost:3000/node_modules/zone.js/dist/zone.min.js:1:16239)
    at n.args.(anonymous function) (http://localhost:3000/node_modules/zone.js/dist/zone.min.js:1:3513)
(anonymous) @ map.js:58
e.invokeTask @ zone.min.js:1
n.runTask @ zone.min.js:1
invoke @ zone.min.js:1
n.args.(anonymous function) @ zone.min.js:1

**Comment by NDMO** [comment]
@aellis , ok i think i have fixed the issues i was having. Merge conflict fixed, and cannot read data of undefined fixed.  Also added a check so the delay wasn't continually growing out of control. Should be good to merge now.

**Pull request merged**
