### PR TITLE
Rma updates

### LINKED ISSUE #86: Sales Rep - RMA Inquiry - Revisions Requested
On RMA inquiry, we want it to work like the other inquiry screens, so make the following changes:

- It should automatically filter by the selected account.
- Due to the above, we can hide the customer name column.
- The filter box didn't seem to do anything for me.  For consistency, remove it or add a similar functioning filter to all of the other inquiry screens.
- The column alignment in the drill-downs is off.
- On quantity columns, do a right-align.
- On the drill-down view the column headers click as if they would be sortable but are not sorting. Either disable the clicking to make them not appear sortable or fix the sorting.
- See if you can get the height of the date fields to match that of the search button.

### PR DESCRIPTION
**Pull request by NDMO**
Closes #86 . Let me know if there are any other changes needed.

### CODE REVIEW

**Comment by aellis** [comment]
Can you beautify the contents of your BezlExport.txt and save that into your commit?  Here is a nice site to do that on:

http://codebeautify.org/jsonviewer

**Comment by aellis** [comment]
@NDMO I am still not seeing this with the beautified output.  The main reason I am looking for this is to assist in resolving the merge conflict I am seeing on it.

**Comment by NDMO** [comment]
@aellis My apologies, totally slipped my mind. I will do that for you right now

**Comment by NDMO** [comment]
@aellis should be good to go now, looks like markup is still a string thou.

**Pull request merged**
