### PR TITLE
Sales rep   accounts view   data disappears due to data cache #151

### PR DESCRIPTION
**Pull request by bitingmidge**
Resolve issue #151

### CODE REVIEW

**Comment by bitingmidge** [comment]
@aellis - So I still had the URL references to my feature branch in the BezelExport.txt file that needed changed to --> https://bezlio-apps-dev.bezl.io/...

How do you want this to work in the future? Fix up the URLs before commit?

**Comment by aellis** [comment]
@bitingmidge yeah, since we are now in a place where commits to either dev or master will be automatically pushed to users I think it is best if pull request come through with the corrected URL.

**Comment by bitingmidge** [comment]
@aellis - One issue with that though is there is no easy way for an admin to test a pull request before merging it into dev.

**Comment by aellis** [comment]
@bitingmidge The way I would see that is when it is in dev it is the spot for testing prior to commit to master.  And if major issues arise we could revert the pull request.  Think that could work?

**Comment by bitingmidge** [comment]
@aellis That will work. I just submitted pull request #160 to correct the URL path for the accounts bezl.

**Pull request merged**
